// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCUUzlqyf5ZINXnfb4p22w-k3i0TSUDJE',
    appId: '1:80490163324:web:3f186c2d9d8e119055adf9',
    messagingSenderId: '80490163324',
    projectId: 'login-sanber',
    authDomain: 'login-sanber.firebaseapp.com',
    storageBucket: 'login-sanber.appspot.com',
    measurementId: 'G-J34447SWDK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4MTSXhRIwHJdy8FQBA_kwoMseyS60doc',
    appId: '1:80490163324:android:f080a3782d4639bd55adf9',
    messagingSenderId: '80490163324',
    projectId: 'login-sanber',
    storageBucket: 'login-sanber.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF0ieo3MM9PSuJHIzOwXSidcQ6gkSx5KQ',
    appId: '1:80490163324:ios:60ee91243b3cd37f55adf9',
    messagingSenderId: '80490163324',
    projectId: 'login-sanber',
    storageBucket: 'login-sanber.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF0ieo3MM9PSuJHIzOwXSidcQ6gkSx5KQ',
    appId: '1:80490163324:ios:60ee91243b3cd37f55adf9',
    messagingSenderId: '80490163324',
    projectId: 'login-sanber',
    storageBucket: 'login-sanber.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCUUzlqyf5ZINXnfb4p22w-k3i0TSUDJE',
    appId: '1:80490163324:web:e1245f9cc61f866f55adf9',
    messagingSenderId: '80490163324',
    projectId: 'login-sanber',
    authDomain: 'login-sanber.firebaseapp.com',
    storageBucket: 'login-sanber.appspot.com',
    measurementId: 'G-VH1T3WJWWR',
  );
}
